from datetime import datetime
from fastapi import HTTPException
from fastapi import APIRouter
from app.services.decision_engine import DecisionEngine
from app.api.schemas import ContextRequest, ContextResponse
from app.domain.context_models import ContextRecord
from app.services.context_store import ContextStore
from app.services.store_instance import store
from app.api.tick_schema import TickRequest
from app.domain.actions import Action, TickResponse

router = APIRouter()

store = ContextStore()
engine = DecisionEngine()


@router.get("/v1/healthz")
def health():
    return {
        "status": "ok",
        "uptime_seconds": 0,
        "contexts_loaded": {
            "category": len(store.categories),
            "merchant": len(store.merchants),
            "customer": len(store.customers),
            "trigger": len(store.triggers),
        },
    }


@router.post("/v1/context", response_model=ContextResponse)
def push_context(request: ContextRequest):

    record = ContextRecord(
        context_id=request.context_id,
        version=request.version,
        delivered_at=request.delivered_at,
        payload=request.payload,
    )

    mapping = {
        "category": store.upsert_category,
        "merchant": store.upsert_merchant,
        "customer": store.upsert_customer,
        "trigger": store.upsert_trigger,
    }

    accepted = mapping[request.scope](record)

    if not accepted:
        current = getattr(store, f"{request.scope}s")[request.context_id]

        return ContextResponse(
            accepted=False,
            reason="stale_version",
            current_version=current.version,
        )

    return ContextResponse(
        accepted=True,
        ack_id=f"ack_{request.context_id}_v{request.version}",
        stored_at=datetime.utcnow(),
    )

@router.post("/v1/tick", response_model=TickResponse)
def tick(request: TickRequest):

    actions = []

    for trigger_id in request.available_triggers:

        trigger = store.triggers.get(trigger_id)

        if trigger is None:
            continue

        payload = trigger.payload

        merchant_id = payload.get("merchant_id")

        merchant = store.merchants.get(merchant_id)

        if merchant is None:
            continue

        category_slug = merchant.payload.get("category_slug")

        category = store.categories.get(category_slug)

        if category is None:
            continue

        action = Action(
            conversation_id=f"conv_{trigger_id}",
            merchant_id=merchant_id,
            customer_id=payload.get("customer_id"),
            send_as="vera",
            trigger_id=trigger_id,
            template_name="dynamic_v1",
            template_params=[],
            body="placeholder",
            cta="open_ended",
            suppression_key=payload.get("suppression_key", trigger_id),
            rationale="Generated by Vera.",
        )

        actions.append(action)

    return TickResponse(actions=actions)