from pydantic import BaseModel, Field

from app.domain.enums import Priority, Sender, Strategy


class DecisionPlan(BaseModel):
    """
    Internal execution plan generated by the Decision Engine.
    """

    strategy: Strategy

    priority: Priority

    score: float

    confidence: float = Field(ge=0.0, le=1.0)

    sender: Sender

    cta: str

    reasoning: list[str] = Field(default_factory=list)